const REGULAR_PURCHASE = 1000;
const ONE_PERCENT = 0.01;

const INCREASED_PURCHASE = 2000;
const FIVE_PERCENT = 0.05;

const SPECIAL_PURCHASE = 30000000;
const THIRTEEN_PERCENT = 0.3;

const CASHBACK_LIMIT = 3000;
let cashback = REGULAR_PURCHASE * ONE_PERCENT + 
INCREASED_PURCHASE * FIVE_PERCENT + 
SPECIAL_PURCHASE * THIRTEEN_PERCENT;

    if (cashback > CASHBACK_LIMIT) {
    cashback = CASHBACK_LIMIT
}
console.log(cashback)